// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/user.proto

package request

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserFeatures_RegisterUser_FullMethodName = "/users.UserFeatures/RegisterUser"
	UserFeatures_Login_FullMethodName        = "/users.UserFeatures/Login"
)

// UserFeaturesClient is the client API for UserFeatures service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserFeaturesClient interface {
	RegisterUser(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Response, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error)
}

type userFeaturesClient struct {
	cc grpc.ClientConnInterface
}

func NewUserFeaturesClient(cc grpc.ClientConnInterface) UserFeaturesClient {
	return &userFeaturesClient{cc}
}

func (c *userFeaturesClient) RegisterUser(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, UserFeatures_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFeaturesClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, UserFeatures_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserFeaturesServer is the server API for UserFeatures service.
// All implementations must embed UnimplementedUserFeaturesServer
// for forward compatibility.
type UserFeaturesServer interface {
	RegisterUser(context.Context, *Person) (*Response, error)
	Login(context.Context, *LoginRequest) (*Response, error)
	mustEmbedUnimplementedUserFeaturesServer()
}

// UnimplementedUserFeaturesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserFeaturesServer struct{}

func (UnimplementedUserFeaturesServer) RegisterUser(context.Context, *Person) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedUserFeaturesServer) Login(context.Context, *LoginRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserFeaturesServer) mustEmbedUnimplementedUserFeaturesServer() {}
func (UnimplementedUserFeaturesServer) testEmbeddedByValue()                      {}

// UnsafeUserFeaturesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserFeaturesServer will
// result in compilation errors.
type UnsafeUserFeaturesServer interface {
	mustEmbedUnimplementedUserFeaturesServer()
}

func RegisterUserFeaturesServer(s grpc.ServiceRegistrar, srv UserFeaturesServer) {
	// If the following call pancis, it indicates UnimplementedUserFeaturesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserFeatures_ServiceDesc, srv)
}

func _UserFeatures_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFeaturesServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFeatures_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFeaturesServer).RegisterUser(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFeatures_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFeaturesServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFeatures_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFeaturesServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserFeatures_ServiceDesc is the grpc.ServiceDesc for UserFeatures service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserFeatures_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserFeatures",
	HandlerType: (*UserFeaturesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserFeatures_RegisterUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserFeatures_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
